### ISSUE TITLE
Select or enter allocation Id

### ISSUE THREAD

**Issue by cameotisha** [chailmis/chailmis-android#63]
- [x] when syncing, the user should select allocation number from a drop down
- [x] when the app is not syncing, the user should be able to enter the allocation number of the stock received
- [x] this allocation number should match the SRV number on orders where this allocation was made.
- [x] logic should check that format of allocation number is correct.
- [x] logic should check that the same allocation number is not used for multiple orders.
